services:
  perception:
    build: .
    image: final_year_project:phase2
    container_name: fyp-phase2-engine

    ipc: host

    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./uploads:/app/uploads

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HEADLESS=True

    env_file:
      - .env
    
    ports:
      - "5000:5000"